apiVersion: v1
kind: Pod
metadata:
  name: kuvuln-test-pod
spec:
  containers:
  - name: exploit-container
    image: nginx:latest
    securityContext:
      privileged: true
      runAsUser: 0
    env:
    - name: AWS_SECRET_ACCESS_KEY
      value: "AKIAIMORU6EVALUETEST"
