apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-pod
  annotations:
    description: "POD INSEGURO PARA PRUEBAS DE KUVULN"
spec:
  containers:
  - name: exploit-container
    image: nginx:latest
    # ERROR 1: Correr como root (Privileged)
    securityContext:
      privileged: true
      runAsUser: 0 
    
    # ERROR 2: Secretos quemados en variables de entorno (Hardcoded Secrets)
    env:
    - name: AWS_ACCESS_KEY_ID
      value: "AKIAIOSFODNN7EXAMPLE"
    - name: DB_PASSWORD
      value: "admin12345"

    # ERROR 3: Sin límites de recursos (DoS risk)
    resources: {}

    # ERROR 4: Montar el socket de Docker (Escape de contenedor)
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket

  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
